allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@igorskyflyer/biome-config@3.0.0 || 3.0.2'
  - '@igorskyflyer/tsconfig@2.0.1'

onlyBuiltDependencies:
  - esbuild

overrides:
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  postcss@<8.5.10: ^8.5.10
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'
  vite: '>=7.3.5'
